#!/bin/sh /etc/rc.common
START=99
STOP=15
USE_PROCD=1


PROG=/usr/bin/lucky

start_service() {
	local enabled configdir
	enabled="$(uci -q get lucky.@lucky[0].enabled)"
	configdir="$(uci -q get lucky.@lucky[0].configdir)"
	[ "$enabled" = 1 ] || return 0
	[ -x "$PROG" ] || return 1
	[ -n "$configdir" ] || configdir='/etc/config/lucky.daji'
	mkdir -p "$configdir" || return 1

	procd_open_instance main
	procd_set_param command "$PROG" -cd "$configdir"
	procd_set_param respawn
	procd_set_param file "$PROG" /etc/config/lucky
	procd_set_param term_timeout 10
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger lucky
}
